language: python
python:
  - "3.9"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python day1/day1test.py || python3 day1/day1test.py
  - python day2/day2test.py || python3 day2/day2test.py
  - python day3/day3test.py || python3 day3/day3test.py
  - python day4/day4test.py || python3 day4/day4test.py
  - python day5/day5test.py || python3 day5/day5test.py
  - python day6/day6test.py || python3 day6/day6test.py
  - python day7/day7test.py || python3 day7/day7test.py
  - python day8/day8test.py || python3 day8/day8test.py
  - python day9/day9test.py || python3 day9/day9test.py
  - python day10/day10test.py || python3 day10/day10test.py
  - python day11/day11test.py || python3 day11/day11test.py
  - python day12/day12test.py || python3 day12/day12test.py
  - python day13/day13test.py || python3 day13/day13test.py
  - python day14/day14test.py || python3 day14/day14test.py
  - python day15/day15test.py || python3 day15/day15test.py
  - python day16/day16test.py || python3 day16/day16test.py
  - python day17/day17test.py || python3 day17/day17test.py
  - python day18/day18test.py || python3 day18/day18test.py
  - python day19/day19test.py || python3 day19/day19test.py
  - python day20/day20test.py || python3 day20/day20test.py
  - python day21/day21test.py || python3 day21/day21test.py
  - python day22/day22test.py || python3 day22/day22test.py
  - python day23/day23test.py || python3 day23/day23test.py
  - python day24/day24test.py || python3 day24/day24test.py
  - python day25/day25test.py || python3 day25/day25test.py


